-- ============================================================
-- Clstr CA Portal — Initial Schema Migration
-- Standard SQL format compatible with Supabase SQL Editor and CLI
-- ============================================================

-- Enable pgcrypto for password hashing in trigger/RPC functions
create extension if not exists "pgcrypto";

-- ─── 1. Custom Enums ─────────────────────────────────────────────────────────

do $$
begin
  if not exists (select 1 from pg_type where typname = 'user_role') then
    create type public.user_role as enum ('MEMBER', 'LEAD', 'SUPER_ADMIN');
  end if;
  if not exists (select 1 from pg_type where typname = 'task_status') then
    create type public.task_status as enum ('open', 'pending', 'verified', 'rejected');
  end if;
  if not exists (select 1 from pg_type where typname = 'task_category') then
    create type public.task_category as enum (
      'Registration & Onboarding',
      'Campus Growth & Outreach',
      'Event & Workshop Execution',
      'Community & Content'
    );
  end if;
end;
$$;

-- ─── 2. Base Tables ──────────────────────────────────────────────────────────

-- Teams
create table if not exists public.teams (
  id            uuid primary key default gen_random_uuid(),
  college       text not null,
  tier          int not null default 4 check (tier between 1 and 4),
  lead_id       uuid,  -- FK added after profiles created
  target_users  int not null default 1000,
  created_at    timestamptz default now()
);

-- Profiles (extends auth.users 1-to-1)
create table if not exists public.profiles (
  id            uuid primary key references auth.users(id) on delete cascade,
  full_name     text not null,
  college       text,
  avatar_url    text,
  role          public.user_role not null default 'MEMBER',
  team_id       uuid references public.teams(id),
  tier          int default 4,
  total_points  int not null default 0,
  created_at    timestamptz default now()
);

-- Add foreign key back to profiles from teams.lead_id
do $$
begin
  if not exists (
    select 1 from information_schema.table_constraints
    where constraint_name = 'teams_lead_id_fkey'
  ) then
    alter table public.teams
      add constraint teams_lead_id_fkey
      foreign key (lead_id) references public.profiles(id)
      on delete set null;
  end if;
end;
$$;

-- Invites (reusable or single-use join codes generated by LEAD / SUPER_ADMIN)
create table if not exists public.invites (
  id            uuid primary key default gen_random_uuid(),
  code          text unique not null,
  team_id       uuid references public.teams(id) on delete cascade not null,
  created_by    uuid references public.profiles(id) on delete set null,
  used_by       uuid references public.profiles(id) on delete set null,
  domain_role   text,  -- optional: "Design Lead", "Growth Rep", etc.
  created_at    timestamptz default now(),
  used_at       timestamptz,
  expires_at    timestamptz
);

-- Task Definitions (managed by SUPER_ADMIN)
create table if not exists public.task_definitions (
  id            uuid primary key default gen_random_uuid(),
  title         text not null,
  description   text,
  points        int not null default 100,
  category      public.task_category not null,
  active        boolean not null default true,
  week_assigned int check (week_assigned between 1 and 13),
  created_at    timestamptz default now()
);

-- Task Submissions
create table if not exists public.task_submissions (
  id            uuid primary key default gen_random_uuid(),
  task_id       uuid references public.task_definitions(id) on delete cascade not null,
  user_id       uuid references public.profiles(id) on delete cascade not null,
  status        public.task_status not null default 'open',
  proof_url     text,
  notes         text,
  reviewed_by   uuid references public.profiles(id),
  rejection_reason text,
  points_awarded int default 0,
  submitted_at  timestamptz default now(),
  reviewed_at   timestamptz,
  unique (task_id, user_id)
);

-- Weekly Reports
create table if not exists public.weekly_reports (
  id              uuid primary key default gen_random_uuid(),
  user_id         uuid references public.profiles(id) on delete cascade not null,
  week            int not null check (week between 1 and 13),
  signups_count   int not null default 0,
  reels_posted    int not null default 0,
  active_clubs    int not null default 0,
  big_win         text,
  blocker         text,
  submitted_at    timestamptz default now(),
  unique (user_id, week)
);

-- Reels Tracker
create table if not exists public.reels (
  id            uuid primary key default gen_random_uuid(),
  user_id       uuid references public.profiles(id) on delete cascade not null,
  week          int not null check (week between 1 and 13),
  reel_type     text not null,  -- "launch", "event", "club_highlight", etc.
  url           text,
  posted        boolean not null default false,
  posted_date   date,
  created_at    timestamptz default now()
);

-- Clubs Onboarded
create table if not exists public.clubs (
  id              uuid primary key default gen_random_uuid(),
  team_id         uuid references public.teams(id) on delete cascade not null,
  user_id         uuid references public.profiles(id) on delete cascade not null,
  name            text not null,
  category        text not null,  -- "Tech", "Cultural", "Sports", "Literary"
  president_name  text,
  president_contact text,
  first_event_date date,
  active          boolean not null default true,
  created_at      timestamptz default now()
);

-- Notifications
create table if not exists public.notifications (
  id            uuid primary key default gen_random_uuid(),
  user_id       uuid references public.profiles(id) on delete cascade not null,
  type          text not null,  -- "task_approved", "task_rejected", "invite_accepted", "milestone_unlocked"
  payload       jsonb default '{}'::jsonb,
  read          boolean not null default false,
  created_at    timestamptz default now()
);

-- ─── 3. Row-Level Security (RLS) Setup ───────────────────────────────────────

alter table public.profiles          enable row level security;
alter table public.teams             enable row level security;
alter table public.invites           enable row level security;
alter table public.task_definitions  enable row level security;
alter table public.task_submissions  enable row level security;
alter table public.weekly_reports    enable row level security;
alter table public.reels             enable row level security;
alter table public.clubs             enable row level security;
alter table public.notifications     enable row level security;

-- ── Helpers ──────────────────────────────────────────────────────────────────

drop function if exists public.my_team_id() cascade;
create or replace function public.my_team_id()
returns uuid language sql stable security definer as $$
  select team_id from public.profiles where id = auth.uid();
$$;

drop function if exists public.is_super_admin() cascade;
create or replace function public.is_super_admin()
returns boolean language sql stable security definer as $$
  select exists (
    select 1 from public.profiles
    where id = auth.uid() and role = 'SUPER_ADMIN'
  );
$$;

drop function if exists public.is_lead_or_admin() cascade;
create or replace function public.is_lead_or_admin()
returns boolean language sql stable security definer as $$
  select exists (
    select 1 from public.profiles
    where id = auth.uid() and role in ('LEAD', 'SUPER_ADMIN')
  );
$$;

-- ── Profiles policies ──────────────────────────────────────────────────────────
drop policy if exists "profiles: own read" on public.profiles;
create policy "profiles: own read"
  on public.profiles for select
  using (id = auth.uid() or public.is_lead_or_admin());

drop policy if exists "profiles: own update" on public.profiles;
create policy "profiles: own update"
  on public.profiles for update
  using (id = auth.uid());

drop policy if exists "profiles: insert own" on public.profiles;
create policy "profiles: insert own"
  on public.profiles for insert
  with check (id = auth.uid());

drop policy if exists "profiles: super admin full" on public.profiles;
create policy "profiles: super admin full"
  on public.profiles for all
  using (public.is_super_admin());

-- ── Teams policies ─────────────────────────────────────────────────────────────
drop policy if exists "teams: member can read own team" on public.teams;
create policy "teams: member can read own team"
  on public.teams for select
  using (id = public.my_team_id() or public.is_super_admin());

drop policy if exists "teams: lead can update own team" on public.teams;
create policy "teams: lead can update own team"
  on public.teams for update
  using (lead_id = auth.uid() or public.is_super_admin());

drop policy if exists "teams: super admin full" on public.teams;
create policy "teams: super admin full"
  on public.teams for all
  using (public.is_super_admin());

-- ── Invites policies ───────────────────────────────────────────────────────────
drop policy if exists "invites: lead can create for own team" on public.invites;
create policy "invites: lead can create for own team"
  on public.invites for insert
  with check (team_id = public.my_team_id() and public.is_lead_or_admin());

drop policy if exists "invites: lead can read own team invites" on public.invites;
create policy "invites: lead can read own team invites"
  on public.invites for select
  using (team_id = public.my_team_id() or public.is_super_admin());

drop policy if exists "invites: anyone can validate a code (for signup)" on public.invites;
create policy "invites: anyone can validate a code (for signup)"
  on public.invites for select
  using (true);

drop policy if exists "invites: lead can update own team invites" on public.invites;
create policy "invites: lead can update own team invites"
  on public.invites for update
  using (team_id = public.my_team_id() or public.is_super_admin());

-- ── Task definitions policies ──────────────────────────────────────────────────
drop policy if exists "task_definitions: all authenticated can read" on public.task_definitions;
create policy "task_definitions: all authenticated can read"
  on public.task_definitions for select
  using (auth.uid() is not null and active = true);

drop policy if exists "task_definitions: super admin full" on public.task_definitions;
create policy "task_definitions: super admin full"
  on public.task_definitions for all
  using (public.is_super_admin());

-- ── Task submissions policies ──────────────────────────────────────────────────
drop policy if exists "task_submissions: own read" on public.task_submissions;
create policy "task_submissions: own read"
  on public.task_submissions for select
  using (user_id = auth.uid() or public.is_lead_or_admin());

drop policy if exists "task_submissions: own insert" on public.task_submissions;
create policy "task_submissions: own insert"
  on public.task_submissions for insert
  with check (user_id = auth.uid());

drop policy if exists "task_submissions: own update (submit/retry)" on public.task_submissions;
create policy "task_submissions: own update (submit/retry)"
  on public.task_submissions for update
  using (user_id = auth.uid() and status in ('open','rejected'));

drop policy if exists "task_submissions: lead reviews team submissions" on public.task_submissions;
create policy "task_submissions: lead reviews team submissions"
  on public.task_submissions for select
  using (
    exists (
      select 1 from public.profiles p
      where p.id = task_submissions.user_id
        and p.team_id = public.my_team_id()
    )
    or public.is_super_admin()
  );

drop policy if exists "task_submissions: lead updates team submissions" on public.task_submissions;
create policy "task_submissions: lead updates team submissions"
  on public.task_submissions for update
  using (
    public.is_lead_or_admin()
    and exists (
      select 1 from public.profiles p
      where p.id = task_submissions.user_id
        and p.team_id = public.my_team_id()
    )
  );

drop policy if exists "task_submissions: super admin full" on public.task_submissions;
create policy "task_submissions: super admin full"
  on public.task_submissions for all
  using (public.is_super_admin());

-- ── Weekly reports policies ────────────────────────────────────────────────────
drop policy if exists "weekly_reports: own read/write" on public.weekly_reports;
create policy "weekly_reports: own read/write"
  on public.weekly_reports for all
  using (user_id = auth.uid());

drop policy if exists "weekly_reports: lead read team" on public.weekly_reports;
create policy "weekly_reports: lead read team"
  on public.weekly_reports for select
  using (
    exists (
      select 1 from public.profiles p
      where p.id = weekly_reports.user_id and p.team_id = public.my_team_id()
    )
    or public.is_super_admin()
  );

-- ── Reels policies ─────────────────────────────────────────────────────────────
drop policy if exists "reels: own read/write" on public.reels;
create policy "reels: own read/write"
  on public.reels for all
  using (user_id = auth.uid());

drop policy if exists "reels: lead read team" on public.reels;
create policy "reels: lead read team"
  on public.reels for select
  using (
    exists (
      select 1 from public.profiles p
      where p.id = reels.user_id and p.team_id = public.my_team_id()
    )
    or public.is_super_admin()
  );

-- ── Clubs policies ─────────────────────────────────────────────────────────────
drop policy if exists "clubs: team members read own team clubs" on public.clubs;
create policy "clubs: team members read own team clubs"
  on public.clubs for select
  using (team_id = public.my_team_id() or public.is_super_admin());

drop policy if exists "clubs: own write" on public.clubs;
create policy "clubs: own write"
  on public.clubs for all
  using (user_id = auth.uid() or public.is_lead_or_admin());

-- ── Notifications policies ─────────────────────────────────────────────────────
drop policy if exists "notifications: own read/update" on public.notifications;
create policy "notifications: own read/update"
  on public.notifications for select
  using (user_id = auth.uid());

drop policy if exists "notifications: own update (mark read)" on public.notifications;
create policy "notifications: own update (mark read)"
  on public.notifications for update
  using (user_id = auth.uid());

drop policy if exists "notifications: service can insert" on public.notifications;
create policy "notifications: service can insert"
  on public.notifications for insert
  with check (true);

-- ─── Trigger: auto-create profile on signup ───────────────────────────────────
create or replace function public.handle_new_user()
returns trigger language plpgsql security definer as $$
begin
  insert into public.profiles (id, full_name, college, role)
  values (
    new.id,
    coalesce(new.raw_user_meta_data->>'full_name', split_part(new.email, '@', 1)),
    coalesce(new.raw_user_meta_data->>'college', ''),
    coalesce(new.raw_user_meta_data->>'role', 'MEMBER')::public.user_role
  );
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- ─── Trigger: update profiles.total_points when submission verified ───────────
create or replace function public.handle_submission_verified()
returns trigger language plpgsql security definer as $$
begin
  if new.status = 'verified' and old.status != 'verified' then
    update public.profiles
    set total_points = total_points + new.points_awarded
    where id = new.user_id;
  end if;
  if old.status = 'verified' and new.status != 'verified' then
    update public.profiles
    set total_points = greatest(0, total_points - old.points_awarded)
    where id = old.user_id;
  end if;
  return new;
end;
$$;

drop trigger if exists on_submission_verified on public.task_submissions;
create trigger on_submission_verified
  after update on public.task_submissions
  for each row execute procedure public.handle_submission_verified();
